export const ROUTES = {
  HOME:            "/",
  SHOP:            "/shop",
  PRODUCT:         "/product/:slug",
  CATEGORIES:      "/categories",
  BRANDS:          "/brands",
  CART:            "/cart",
  WISHLIST:        "/wishlist",
  CHECKOUT:        "/checkout",
  LOGIN:           "/login",
  REGISTER:        "/register",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD:  "/reset-password",
  ABOUT:           "/about",
  CONTACT:         "/contact",
  FAQ:             "/faq",

  USER: {
    DASHBOARD:       "/user/dashboard",
    PROFILE:         "/user/profile",
    CHANGE_PASSWORD: "/user/change-password",
    ORDERS:          "/user/orders",
    ORDER_DETAIL:    "/user/orders/:id",
    WISHLIST:        "/user/wishlist",
    ADDRESSES:       "/user/addresses",
    NOTIFICATIONS:   "/user/notifications",
  },

  ADMIN: {
    DASHBOARD:   "/admin/dashboard",
    PRODUCTS:    "/admin/products",
    ADD_PRODUCT: "/admin/products/add",
    EDIT_PRODUCT:"/admin/products/edit/:id",
    CATEGORIES:  "/admin/categories",
    BRANDS:      "/admin/brands",
    ORDERS:      "/admin/orders",
    ORDER_DETAIL:"/admin/orders/:id",
    CUSTOMERS:   "/admin/customers",
    USERS:       "/admin/users",
    REVIEWS:     "/admin/reviews",
    COUPONS:     "/admin/coupons",
    REPORTS:     "/admin/reports",
    SETTINGS:    "/admin/settings",
  },
};
